//! Typed contract interaction — `Contract<P>` + `CallBuilder` + Event
//! filters. The dapp-facing dispatch surface generated by the
//! [`pyde_abi!`] macro plugs in here.
//!
//! ## T7 stub
//!
//! Real implementation lands in T10 (Phase A3). This module will own:
//!
//! - [`Contract<P: Provider>`] — typed wrapper over an address + a
//!   provider. Equivalent to alloy's `ContractInstance`.
//! - [`CallBuilder<P, Args, Ret>`] — fluent build for a single contract
//!   call. Chain `.gas_limit(...)`, `.value(...)`, `.signer(&wallet)`,
//!   then `.send()` (state-mutating) or `.call()` (read-only) for
//!   execution. `.send()` returns a [`crate::provider::PendingTx`];
//!   `.call()` returns the decoded return value directly.
//! - Typed calldata encoder/decoder for every Pyde primitive:
//!   `bool`, `u8..u128`, `i8..i128`, `U256` / `I256` (via `ruint`),
//!   `Address`, `String`, `Vec<u8>`, `Vec<T>`. Encoding matches the
//!   Borsh convention used by Otigen-generated contracts.
//! - Event filter helpers — produce `LogFilter`s typed to a specific
//!   event signature, decode incoming `Log`s back to typed events.
//!
//! Note on the [`pyde_abi!`] macro: the proc-macro lives in the
//! sibling `pyde-sdk-macros` crate (Rust requires `proc-macro = true`
//! crates to be standalone). This crate re-exports it as
//! `pub use pyde_sdk_macros::pyde_abi;` for the user-facing API.
//!
//! Selector convention: `selector = Blake3(function_name)[..4]` per
//! [`HOST_FN_ABI_SPEC §3.7`]. The current pyde-crypto-wasm uses
//! FNV-1a — that's a drift to resolve before T10 ships (see T3 action
//! items A1 + A4).
